### ISSUE TITLE
Implementation of CoinOS in Meteor (Due Dec 6th)

### ISSUE THREAD

**Issue by shayanb** [bitcoinembassy/bitcoin-pos#7]
Implementing core functionality of coinos in meteor

**Due Date: Saturday December 6th, 2014**

**Comment by shayanb** [comment]
@frabrunelle today is the due date.

**Comment by frabrunelle** [comment]
yes I'll be working on doing that with Guillaume at the Bitcoin Embassy. And tomorrow too.
